name: Publish a new release
on:
  push:
    tags:
      - 'v*'
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4.1.1
      - name: 'Setup Go action'
        uses: actions/setup-go@v5.0.0
        with:
          go-version: ${{ inputs.go_version }}
      - name: 'Install yaml linter'
        run: go install github.com/google/yamlfmt/cmd/yamlfmt@v0.16.0
      - name: 'Run linters'
        run: yamlfmt -lint -conf .yamlfmt.yml .
  release:
    needs: [lint]
    uses: .github/workflows/global/release.yml@main
    with:
      is_a_prerelease: false
    secrets: inherit
