name: Action - Flutter test
on:
  workflow_call:
    inputs:
      flutter_version:
        description: 'The Flutter used (ex: 2.5.1)'
        required: true
        type: string
jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4
      - name: 'Decrypt secret configuration'
        run: ./.github/scripts/decrypt_secret.sh
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - name: 'Check secret configuration'
        run: ./.github/scripts/check_secrets_decryption.sh
      - name: 'Setup flutter action'
        uses: subosito/flutter-action@v2.18.0
        with:
          flutter-version: ${{ inputs.flutter_version }}
      - name: 'Configure Flutter'
        run: |
          flutter config --no-analytics
          flutter config --no-cli-animations
      - name: 'Flutter test (with coverage)'
        run: |
          flutter test --coverage --test-randomize-ordering-seed random
      - name: 'Upload coverage report'
        uses: codecov/codecov-action@v4.6.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
