name: Action - Flutter build
on:
  workflow_call:
    inputs:
      flutter_version:
        description: 'The Flutter used (ex: 2.5.1)'
        required: true
        type: string
      flutter_flavor:
        description: 'Flavor name (dev, beta, or production)'
        required: true
        type: string
      java_version:
        description: 'The Java used (ex: 17.x)'
        required: true
        type: string
      build_android_apk:
        description: 'Build the Android APK version of the application'
        required: false
        default: 'false'
        type: string
      build_android_aab:
        description: 'Build the Android AppBundle version of the application'
        required: false
        default: 'false'
        type: string
      build_ios:
        description: 'Build the iOS version of the application'
        required: false
        default: 'false'
        type: string
      build_web:
        description: 'Build the WEB version of the application'
        required: false
        default: 'false'
        type: string
      build_number:
        description: 'The build number passed to --build-number'
        required: true
        type: string
      build_name:
        description: 'The build name passed to --build-name'
        required: true
        type: string
jobs:
  build_android_apk:
    name: 'Android (APK)'
    if: ${{ inputs.build_android_apk == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v5
      - name: 'Decrypt secret configuration'
        run: ./.github/scripts/decrypt_secret.sh
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - name: 'Check secret configuration'
        run: ./.github/scripts/check_secrets_decryption.sh
      - name: 'Set up JAVA'
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ inputs.java_version }}
      - name: 'Setup Flutter'
        uses: subosito/flutter-action@v2.21.0
        with:
          flutter-version: ${{ inputs.flutter_version }}
      - name: 'Configure Flutter'
        run: |
          flutter config --no-analytics
          flutter config --no-cli-animations
      - name: 'Build Android APK'
        run: flutter build apk --dart-define=FLAVOR=${{ inputs.flutter_flavor }} --build-number=${{ inputs.build_number }} --build-name=${{ inputs.build_name }} --split-per-abi
      - name: 'Save build results (apk)'
        uses: actions/upload-artifact@v4
        with:
          name: 'android-apk'
          path: build/app/outputs/apk/release/*.apk
  build_android_appbundle:
    name: 'Android (AAB)'
    if: ${{ inputs.build_android_aab == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v5
      - name: 'Decrypt secret configuration'
        run: ./.github/scripts/decrypt_secret.sh
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - name: 'Check secret configuration'
        run: ./.github/scripts/check_secrets_decryption.sh
      - name: 'Set up JAVA'
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ inputs.java_version }}
      - name: 'Setup Flutter'
        uses: subosito/flutter-action@v2.21.0
        with:
          flutter-version: ${{ inputs.flutter_version }}
      - name: 'Configure Flutter'
        run: |
          flutter config --no-analytics
          flutter config --no-cli-animations
      - name: 'Build Android App Bundle'
        run: flutter build appbundle --dart-define=FLAVOR=${{ inputs.flutter_flavor }} --build-number=${{ inputs.build_number }} --build-name=${{ inputs.build_name }}
      - name: 'Save build results (apk)'
        uses: actions/upload-artifact@v4
        with:
          name: 'android-aab'
          path: build/app/outputs/bundle/release/*.aab
  build_ios:
    name: 'iOS'
    if: ${{ inputs.build_ios == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: '🥺'
        run: echo 'WIP'
  build_web:
    name: 'WEB'
    if: ${{ inputs.build_web == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: '🥺'
        run: echo 'WIP'
