name: Action - Release
on:
  workflow_call:
    inputs:
      prerelease_suffix:
        description: 'Suffix to designate a pre-release verion (ex: -rc for v0.1.0-rc)'
        required: true
        type: string
jobs:
  changelog:
    runs-on: ubuntu-latest
    name: 'Craft the Changelog'
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: 'Compute since and excluded tag'
        if: ${{ !endsWith(github.ref, inputs.prerelease_suffix) }}
        env:
          PRERELEASE_SUFFIX: ${{ inputs.prerelease_suffix }}
        run: |
          echo SINCE_TAG=$(git tag --list --sort=-creatordate | grep -v ${PRERELEASE_SUFFIX} | sed -n '2p') >> $GITHUB_ENV
          echo EXCLUDE_TAGS_REGEX="^v[0-9]\.[0-9]\.[0-9]-$(echo ${PRERELEASE_SUFFIX}$)" >> $GITHUB_ENV
      - name: 'Compute since and excluded (pre-release)'
        if: ${{ endsWith(github.ref, inputs.prerelease_suffix) }}
        env:
          PRERELEASE_SUFFIX: ${{ inputs.prerelease_suffix }}
        run: |
          echo SINCE_TAG=$(git tag --list --sort=-creatordate | grep ${PRERELEASE_SUFFIX} | sed -n '2p') >> $GITHUB_ENV
          echo EXCLUDE_TAGS_REGEX="^v[0-9]\.[0-9]\.[0-9]$" >> $GITHUB_ENV
      - name: "Generate CHANGELOG.md"
        uses: janheinrichmerker/action-github-changelog-generator@v2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG.md
          sinceTag: ${{ env.SINCE_TAG }}
          excludeTagsRegex: ${{ env.EXCLUDE_TAGS_REGEX }}
      - name: 'Upload CHANGELOG.md'
        uses: actions/upload-artifact@v4.3.1
        with:
          name: changelog
          path: CHANGELOG.md
  release:
    runs-on: ubuntu-latest
    name: 'Publish the Release'
    needs: [changelog]
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: 'Download CHANGELOG artifacts'
        uses: actions/download-artifact@v4.1.4
        with:
          path: changelog
          name: changelog
      - name: 'Generate Github release'
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ endsWith(github.ref, inputs.prerelease_suffix) }}
          name: '${{ github.ref_name }} 🚀'
          body_path: changelog/CHANGELOG.md
