name: Default
on:
  push:
    tags:
      - 'v*'
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  release:
    uses: ./.github/workflows/global.release.yml
    with:
      prerelease_suffix: 'rc'
    secrets: inherit
